version: "3.8"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: app-php
    image: dieison-de-moura/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    command: --innodb-use-native-aio=0
    container_name: db-mysql
    image: dieison-de-moura/db
    restart: always
    tty: true
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - "./docker/mysql/docker-entrypoint-initdb.d/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql"
    environment:
      - MYSQL_DATABASE=php_ddd_tdd
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8888:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge